#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGINS="
"

# Exit if any commands fail
set -o errexit

echo "* Remove empty database file"
rm -f /var/lib/soju/main.db

echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Cleanup home/admin because of delegate dataset usage"
rm -rf /home/admin/.[^.]*

echo "* Cleaning up."
rm -rf /root/*

echo "* Cleaning up"
rm -rf /root/*
sm-prepare-image -y
